default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: ervin
  password: samsung

development:
  <<: *default
  database: todolist_development

staging:
  <<: *default
  database: todolist_staging

test:
  <<: *default
  database: todolist_test

production:
  <<: *default
  database: todolist_production